aws_region                = "eu-west-1"
project_id                = "cmtr-dft5l1nz"
bucket_name               = "cmtr-dft5l1nz-bucket-1790705162"
iam_group_name            = "cmtr-dft5l1nz-iam-group"
iam_policy_name           = "cmtr-dft5l1nz-iam-policy"
iam_role_name             = "cmtr-dft5l1nz-iam-role"
iam_instance_profile_name = "cmtr-dft5l1nz-iam-instance-profile"
